import Head from "next/head";
import HomePage from "@pages/home/";
import 'tw-elements';

const Home = () => {     
    return (
        <div>
            <Head>
                <title>Portfolio de Gorkem</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <script src="./TW-ELEMENTS-PATH/dist/js/index.min.js"></script>
            </Head>
            <HomePage />
        </div>
    )
}

export default Home;