import Head from "next/head";
import HomePage from "@pages/home/";  

const Home = () => {     
    return (
        <div>
            <Head>
                <title>Portfolio de Gorkem</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <HomePage />
        </div>
    )
}

export default Home;